# <center><span style="color:Blue">Numpy Basics</span></center>

### What is Numpy?

- The Numpy library is the core libarary for scientific computing (Math/Vectors/Matrices/Tensors(Array)) in python .
- It provides a high-performance multidimensional array object, and tools for working with these arrays'

In [1]:
#importing the numpy library
import numpy as np

In [97]:
# Numpy Array

arr=np.array([1,2,3])
arr1=np.array([[1,2,3],
               [1,2,3],
               [1,2,3]])
arr2=np.array([[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]])
print("The 1-D array is : {0} ".format(arr))
print("The shape of array is:" ,arr.shape)
print("The legth of array is :",len(arr))
print("The dimension of array is :",arr.ndim)
print("The data type of array is :",arr.dtype)
print("The data type of array is :",type(arr))

print("-------------------------------------------")
print("The 2-D array is : ","\n",(arr1))
print("The shape of array is:" ,arr1.shape)
print("The legth of array is :",len(arr1))
print("The dimension of array is :",arr1.ndim)
print("The data type of array is :",arr1.dtype)
print("The data type of array is :",type(arr1))


print("-------------------------------------------")
print("The 3-D array is : ","\n",(arr2))
print("The shape of array is:" ,arr2.shape)
print("The legth of array is :",len(arr2))
print("The dimension of array is :",arr2.ndim)
print("The data type of array is :",arr2.dtype)
print("The data type of array is :",type(arr2))

The 1-D array is : [1 2 3] 
The shape of array is: (3,)
The legth of array is : 3
The dimension of array is : 1
The data type of array is : int32
The data type of array is : <class 'numpy.ndarray'>
-------------------------------------------
The 2-D array is :  
 [[1 2 3]
 [1 2 3]
 [1 2 3]]
The shape of array is: (3, 3)
The legth of array is : 3
The dimension of array is : 2
The data type of array is : int32
The data type of array is : <class 'numpy.ndarray'>
-------------------------------------------
The 3-D array is :  
 [[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]]
The shape of array is: (3, 2, 3)
The legth of array is : 3
The dimension of array is : 3
The data type of array is : int32
The data type of array is : <class 'numpy.ndarray'>


In [96]:
#To create array of zeros

arr_Zeros=np.zeros((1,2))
print("The Array of zeros is :",arr_Zeros)
print("The data type is:",arr_Zeros.dtype)
print("The data type of array is :",type(arr_Zeros))
print("The shape of array is:" ,arr_Zeros.shape)
print("The dimension of array is :",arr_Zeros.ndim)



The Array of zeros is : [[0. 0.]]
The data type is: float64
The data type of array is : <class 'numpy.ndarray'>
The shape of array is: (1, 2)
The dimension of array is : 2


### use of Arange

In [102]:
arr=np.arange(1,9)  #(start,stop,step) >> Default step is one excludes '_stop_'
print(arr) 
arr=np.arange(1,9,2)
print(arr) 

[1 2 3 4 5 6 7 8]
[1 3 5 7]


### Use of LinSpace

In [7]:
#Generates the range of numbers specified(start,stop,no. of numbers to be generated)
lin_1=np.linspace(1,4,9)
lin_1

array([1.   , 1.375, 1.75 , 2.125, 2.5  , 2.875, 3.25 , 3.625, 4.   ])

### Use of Full

In [17]:
#generates array of given dimension with elememts specified,((copies,rows,columns),element of copy)
a=np.full((1,2,2),3)
print(a)
print("------------------------------")
a=np.full((2,3,4),'a')
print(a)



[[[3 3]
  [3 3]]]
------------------------------
[[['a' 'a' 'a' 'a']
  ['a' 'a' 'a' 'a']
  ['a' 'a' 'a' 'a']]

 [['a' 'a' 'a' 'a']
  ['a' 'a' 'a' 'a']
  ['a' 'a' 'a' 'a']]]


### Use of Eye

In [27]:
#identity matrix generation

iden=np.eye(3,dtype=int)
iden

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

# Indexing and Slicing ( 1D , 2D)

In [45]:
ar=np.array([1,2,3,4,5,6])

print("first element is:",ar[0])
print("second element is:",ar[1])
print("last element is:",ar[-1])
print("traversing through array:",ar[0::2]) #start from 0th index and till end with the step 2
print("traversing from specific index:",ar[2:])
print("traversing till specific index:",ar[:2])
print("reversing the array:",ar[::-1])
print("Trversing using negative index :",ar[::-2])






first element is: 1
second element is: 2
last element is: 6
traversing through array: [1 3 5]
traversing from specific index: [3 4 5 6]
traversing till specific index: [1 2]
reversing the array: [6 5 4 3 2 1]
Trversing using negative index : [6 4 2]


In [111]:
age = np.array([23,45,18,26,34,65])
# Retrive the first element 
print('First element :',age[0])
print('Forth element:',age[3])
print('Last element:',age[-1])
print(age[1::2]) # start at 1 st element go up to 65 by the step of 2
print(age[:4])

First element : 23
Forth element: 26
Last element: 65
[45 26 65]
[23 45 18 26]


### 2-D Array

In [91]:
arr1=np.array([[1,2,3],
               [4,5,6]])
print("The array is :\n{0} ".format(arr1))
print("-------------------------------------------------------")
print("Methods of retrieving the elements 2-D of array")
print("-------------------------------------------------------")
print("First elemnent of array:",arr1[0,0])
print("First elemnent of array:",arr1[0][0])
print("Row and column one elemnent of  array:",arr1[1,1])
print("First row of array:",arr1[0])
print("second row of array:",arr1[1])
print("First column of array:",arr1[:,0])
print("second column of array:",arr1[:,1])
print("Checking the array:",arr1[0,0]==arr1[0][0])




The array is :
[[1 2 3]
 [4 5 6]] 
-------------------------------------------------------
Methods of retrieving the elements 2-D of array
-------------------------------------------------------
First elemnent of array: 1
First elemnent of array: 1
Row and column one elemnent of  array: 5
First row of array: [1 2 3]
second row of array: [4 5 6]
First column of array: [1 4]
second column of array: [2 5]
Checking the array: True
2


### Arithmetic operation on array

In [15]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,0])
print("The array_1 is:\n",arr1)
print("----------------------------------")
print("The array_2 is:\n",arr2)
print("----------------------------------")
print("The sum of array1 and array2 is:\n",arr1+arr2)
print("----------------------------------")
print("The subtraction of array1 and array2 is:\n",arr1-arr2)
print("----------------------------------")
print("The multiplication of array1 and array2 is:\n",arr1*arr2)
print("----------------------------------")
print("The division of array1 and array2 is:\n",arr2//arr1)
print("----------------------------------")
print("The square root  of array1  is:\n",np.sqrt(arr1))
print("----------------------------------")
print("The square of array2  is:\n",arr2**2)
print("----------------------------------")
print("The exponential of array2  is:\n",np.exp(arr2))
print("----------------------------------")
print("The log of array1  is:\n",np.log(arr1))

The array_1 is:
 [1 2 3 4 5]
----------------------------------
The array_2 is:
 [6 7 8 9 0]
----------------------------------
The sum of array1 and array2 is:
 [ 7  9 11 13  5]
----------------------------------
The subtraction of array1 and array2 is:
 [-5 -5 -5 -5  5]
----------------------------------
The multiplication of array1 and array2 is:
 [ 6 14 24 36  0]
----------------------------------
The division of array1 and array2 is:
 [6 3 2 2 0]
----------------------------------
The square root  of array1  is:
 [1.         1.41421356 1.73205081 2.         2.23606798]
----------------------------------
The square of array2  is:
 [36 49 64 81  0]
----------------------------------
The exponential of array2  is:
 [4.03428793e+02 1.09663316e+03 2.98095799e+03 8.10308393e+03
 1.00000000e+00]
----------------------------------
The log of array2  is:
 [0.         0.69314718 1.09861229 1.38629436 1.60943791]


## Arithemetic functions


In [19]:
arr1=np.array([1,2,3,4,5])
print("The array_1 is:\n",arr1)
print("----------------------------------")
print("The sum of array elements is:",arr1.sum())
print("----------------------------------")
print("The mean of array elements is:",arr1.mean())
print("The sum of array elements is:",arr1.sum())
print("----------------------------------")
print("The Variance of array elements is:",arr1.var())
print("----------------------------------")
print("The Standard Deviation of array elements is:",arr1.std())
print("----------------------------------")
print("The Square of array elements is:",np.square(arr1))
print("----------------------------------")
print("The min of array elements is:",arr1.min(),"or",np.min(arr1))
print("----------------------------------")
print("The max of array elements is:",arr1.max(),"or",np.max(arr1))
print("----------------------------------")
print("The range of array elements is:",np.max(arr1)-np.min(arr1),"or",arr1.max()-arr1.min())


The array_1 is:
 [1 2 3 4 5]
----------------------------------
The sum of array elements is: 15
----------------------------------
The mean of array elements is: 3.0
The sum of array elements is: 15
----------------------------------
The Variance of array elements is: 2.0
----------------------------------
The Standard Deviation of array elements is: 1.4142135623730951
----------------------------------
The Square of array elements is: [ 1  4  9 16 25]
----------------------------------
The min of array elements is: 1 or 1
----------------------------------
The max of array elements is: 5 or 5
----------------------------------
The range of array elements is: 4 or 4


In [203]:
print('Transpose of A :',np.transpose(A))

Transpose of A : [[1 4]
 [2 5]
 [3 6]]


In [204]:
np.transpose(A).shape

(3, 2)

In [210]:
a = np.array([3,4,5,6,7])
b=np.where(a<5) # retrun an index i at which a[i]<4
print(a[b])

[3 4]


## Transpose, Reshape and Concatenate

In [44]:
arr1=np.array([[1,2,3,4,5],[6,7,8,9,0]])
arr2=np.array([[1,2,3,4,5],[6,7,8,9,0]])
arr3=np.array([1,2,3,4,5])
print("The array_1 is:\n",arr1)
print("-------------------------------------------------------")
print("The array_2 is:\n",arr2)
print("-------------------------------------------------------")
print("The transpose of arr1 is:\n",np.transpose(arr1))
print("-------------------------------------------------------")
print("The shape of array1 is:",arr1.shape)
print("we can reshape the array as 10*1 or 1*10: \n",arr1.reshape(10,1),"\n \n and \n \n",arr1.reshape(1*10))
print("-------------------------------------------------------")
print("concatenation of arr1 and arr2 is :\n",np.concatenate([arr1,arr2]))

The array_1 is:
 [[1 2 3 4 5]
 [6 7 8 9 0]]
-------------------------------------------------------
The array_2 is:
 [[1 2 3 4 5]
 [6 7 8 9 0]]
-------------------------------------------------------
The transpose of arr1 is:
 [[1 6]
 [2 7]
 [3 8]
 [4 9]
 [5 0]]
-------------------------------------------------------
The shape of array1 is: (2, 5)
we can reshape the array as 10*1 or 1*10: 
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]
 [0]] 
 
 and 
 
 [1 2 3 4 5 6 7 8 9 0]
-------------------------------------------------------
concatenation of arr1 and arr2 is :
 [[1 2 3 4 5]
 [6 7 8 9 0]
 [1 2 3 4 5]
 [6 7 8 9 0]]


# Stacking (Array joins)

1. The stack() is used to join two or more arrays of same shape along specified axis
2. we can create higher dimensionl arrays by stacking two or more lower dimensional arrays 

In [55]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,0])
print("The array_1 is:\n",arr1)
print("-------------------------------------------------------")
print("The array_2 is:\n",arr2)
print("-------------------------------------------------------")
print("Stacking of array is\n",np.stack([arr1,arr2])) #default axis is 0
print("-------------------------------------------------------")
print("Stacking of array is\n",np.stack([arr1,arr2],axis=1)) #along axis=1
print("-------------------------------------------------------")
print("Stacking of array horizontally is\n",np.hstack([arr1,arr2]))
print("-------------------------------------------------------")
print("Stacking of array vertically is\n",np.vstack([arr1,arr2]))
print("-------------------------------------------------------")
print("Stacking of array by column is\n",np.column_stack([arr1,arr2]))
print("-------------------------------------------------------")
print("Stacking of array dstack is\n",np.dstack([arr1,arr2]))
print("-------------------------------------------------------")
print("falttening of array is\n",np.ndarray.flatten(arr1))


The array_1 is:
 [1 2 3 4 5]
-------------------------------------------------------
The array_2 is:
 [6 7 8 9 0]
-------------------------------------------------------
Stacking of array is
 [[1 2 3 4 5]
 [6 7 8 9 0]]
-------------------------------------------------------
Stacking of array is
 [[1 6]
 [2 7]
 [3 8]
 [4 9]
 [5 0]]
-------------------------------------------------------
Stacking of array horizontally is
 [1 2 3 4 5 6 7 8 9 0]
-------------------------------------------------------
Stacking of array vertically is
 [[1 2 3 4 5]
 [6 7 8 9 0]]
-------------------------------------------------------
Stacking of array by column is
 [[1 6]
 [2 7]
 [3 8]
 [4 9]
 [5 0]]
-------------------------------------------------------
Stacking of array dstack is
 [[[1 6]
  [2 7]
  [3 8]
  [4 9]
  [5 0]]]
-------------------------------------------------------
falttening of array is
 [1 2 3 4 5]


# flatten the array

In [256]:
arry= np.array([[1,3,5,7],[2,4,6,8]])
print(arry)
print('Dimension :',arry.ndim)
print('Flattened array:', np.ndarray.flatten(arry))
print('Dimension :',np.ndarray.flatten(arry).ndim)

[[1 3 5 7]
 [2 4 6 8]]
Dimension : 2
Flattened array: [1 3 5 7 2 4 6 8]
Dimension : 1


In [261]:
b=arry.reshape(-1,1)

In [262]:
b

array([[1],
       [3],
       [5],
       [7],
       [2],
       [4],
       [6],
       [8]])